
<h1>Création de compte</h1>


<form action="<?= Router::getInstance()->generateUrl("resto_user_create")?>" method="post" enctype="multipart/form-data" autocomplete="on" data-validate>
    <fieldset>
        <div class="row">
            <div class="col-lg-3">

                <label for="forname">Prénom</label>
                <input id="forname" type="text" size="20" maxlength="60" name="forname"  data-required/>
                <br/>

                <label for="lastname">Nom</label>
                <input id="lastname" type="text" size="20" maxlength="60" name="lastname" data-required />
                <br/>

                <label for="address">Adresse</label>
                <input id="address" type="text" size="20" maxlength="60" name="address" data-required/>
                <br/>

                <label for="num-tel">Téléphone</label>
                <input id="num-tel" type="text" size="20" maxlength="60" name="num-tel" data-required />
                <br/>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-3">
                <label for="email">E-mail</label>
                <input id="email" type="text" size="20" maxlength="60" name="email" data-email />
                <br/>

                <label for="pwd">Mot de passe</label>
                <input id="pwd" type="password" size="20" maxlength="60" name="pwd" data-minlength="8" data-equalcopy="password"/>
                <br/>

                <label for="pwd-check">Vérifier le mot de passe</label>
                <input id="pwd-check" type="password" size="20" maxlength="60" name="pwd-check" data-equal="password"/>
                <br/>

                <label for="image">Avatar</label> <br/>

                <input id="image" type="file"  name="image" value=""/>
                <br/>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-3"></div>
            <div class="button-save">
                <input type="submit" value="enregistrer" />
            </div>
        </div>
</form>