

<form  action="<?= Router::getInstance()->generateUrl("resto_user_login") ?>" method="post" enctype="multipart/form-data">

    <div class="form-group">
        <label for="mail">Adresse mail </label>
        <input type="text" class="form-control" id="mail" name="email">
    </div>

    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="remember-me" name="remember-me">
        <label class="form-check-label" for="remember-me">Se souvenir de moi</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
