
<h1>Modification de compte</h1>

<form action="<?= Router::getInstance()->generateUrl("resto_user_update") ?>" method="post" enctype="multipart/form-data" data-validate>
    <div class="form-row">

        <div class="form-group col-md-6">
            <label for="last-name">Prénom</label>
            <input type="text" class="form-control" id="last-name" placeholder="Prénom" name="forname">
        </div>

        <div class="form-group col-md-6">
            <label for="first-name">Nom</label>
            <input type="text" class="form-control" id="first-name" placeholder="Nom" name="lastname">
        </div>

        <div class="form-group col-md-6">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" placeholder="Email" name="email">
        </div>

        <div class="form-group col-md-6">
            <label for="phone-number">Téléphone</label>
            <input type="text" class="form-control" id="phone-number" placeholder="Numérode de téléphone" name="numTel">
        </div>

        <div class="form-group col-md-6">
            <label for="inputAddress">Adresse</label>
            <input type="text" class="form-control" id="inputAddress" placeholder="Adresse" name="adress">
        </div>

        <div class="form-group col-md-6">

        </div>

        <div class="form-group col-md-6">
            <label for="password">Mot de passe</label>
            <input type="password" class="form-control" id="password" placeholder="Mot de passe" name="password">
        </div>

        <div class="form-group col-md-6">
            <label for="checked-password">Confirmer mot de passe</label>
            <input type="password" class="form-control" id="checked-password" placeholder="Confirmation de mot de passe" name="password-checked">
        </div>

        <div class="custom-file">
            <input type="file" class="custom-file-input" id="image-input" value="Choisissez une image" name="image">
            <label class="custom-file-label" for="image-input">Choisir un avatar</label>
        </div>

    </div>

    <div>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </div>
</form>

