<h1>Ajouter un plat</h1>

<form action="<?= Router::getInstance()->generateUrl("resto_dish_create") ?>" method="post" enctype="multipart/form-data" data-validate>

    <div class="form-group " >
        <select class="form-control" id="category" name="category">
            <option value="-1" data-type="-1"><strong>Choisissez une catégorie</strong></option>
            <option value="Entrée">Entrée</option>
            <option value="Plat">Plat</option>
            <option value="Dessert">Dessert</option>
            <option value="Accompagnement">Accompagnement</option>
            <option value="Végan">Végan</option>
            <option value="Viande">Viande</option>
            <option value="Poisson">Poisson</option>
            <option value="Autre">Autre</option>
        </select>
    </div>


    <div class="form-group">
<!--        <label for="dish">Plat</label>-->
        <input type="text" class="form-control" id="dish" name="title"  placeholder="Plat"  data-minlength="3">
    </div>

    <div class="custom-file">
        <input type="file" class="custom-file-input" id="image-input" value="Choisissez une image" name="image" >
        <label class="custom-file-label" for="image-input">Choisir image</label>
    </div>


    <div class="form-group">
<!--        <label for="description">Description</label>-->
        <textarea id="description" class="form-control" name="description"  rows="3" placeholder="Décrivez votre plat" data-minlength="255"></textarea>
    </div>


    <div class="form-group">
<!--           <label for="price">Prix </label>-->
           <input type="text" class="form-control" id="price" name="price" placeholder="Indiquer le prix du plat"  data-type="float" data-optional="0">
    </div>

    <button type="submit" class="btn btn-primary">Enregistrer</button>

</form>
