<!doctype html>
<html lang="fr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    <!-- Bootstrap CSS -->
    <script src="https://kit.fontawesome.com/1901af9c76.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?= $router->getWwwPath()?>/css/normalize.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $router->getWwwPath()?>/css/style.css?b=<?= date("ymdHis")?>">
    <title>Cabo Gosto</title>
</head>
<body>
<header>
    <section class="row justify-content-between">
        <article class="col-sm-4" id="logo">
            <a href="<?= Router::getInstance()->generateUrl("resto_home_main")?>"><img src="<?= $router->getWwwPath()?>/img/logo.jpg" alt="logo"></a>
            <!--<p>Cabo Gosto</p>-->
        </article>
        <article class="col-sm-5" id="portail">

           <?php if ( UserSession::getInstance()->isAuthenticated()):?>
           <div class="row">
                <p class="col-5">Bonjour <strong><?= UserSession::getInstance()->getForname()?></strong></p>
               <a href="<?= Router::getInstance()->generateUrl("resto_user_logout") ?>" id="deconnection">Se déconnecter</a>
           </div>
           <?php else: ?>
               <a href="<?= Router::getInstance()->generateUrl("resto_user_login") ?>">Se connecter</a>
               <br>
               <a href="<?= Router::getInstance()->generateUrl("resto_user_create") ?>">S'inscrire</a>
           <?php endif ;?>

            <?php if (UserSession::getInstance()->isAdmin()):?>
                <a href="<?= Router::getInstance()->generateUrl("resto_admin_interface") ?>"><i class="fab fa-magento"></i></a>
            <?php else: ?>
                <a href="<?= Router::getInstance()->generateUrl("resto_order_show") ?>"><i class="fas fa-shopping-cart"></i></a>
            <?php endif;?>


            <ul class="nav row align-items-end">
                <li class="nav-item">
                    <a href="<?= Router::getInstance()->generateUrl("resto_dish_showall") ?>" class="nav-link navigation" >Tous nos plats</a>
                </li>
                <li class="nav-item">
                    <a href="<?= Router::getInstance()->generateUrl("resto_menu_showall") ?>" class="nav-link navigation" >Tous nos menus</a>
                </li>

                <?php if  (UserSession::getInstance()->isAuthenticated()): ?>
                    <li class="nav-item">
                        <a href="<?= Router::getInstance()->generateUrl("resto_booking_create") ?>" class="nav-link navigation" >Réserver une table</a>
                    </li>
                <?php endif ;?>

            </ul>

        </article>
    </section>
</header>
<aside>
    <?php foreach (Flashbag::getInstance()->consumeAllMessages() as $message):?>
    <div class="flash-message">
       <?= $message?>
    </div>
    <?php endforeach;?>
</aside>
<main class="container">
    <?php include $templatePath ?>
</main>
<footer>
    <section class="row">
        <article class="col-sm-4">
            <p>16 rue de la libération</p>
            <p>Paris</p>
            <p>75017</p>
        </article>
        <article class="col-sm-4">
            <ul>
                <li>Nous contacter</li>
                <li>CGU</li>
                <li>©</li>
            </ul>
        </article>
        <article class="col-sm-4" id="reseau">
            <a href="#"><i class="fab fa-twitter-square"></i></a>
            <a href="#"><i class="fab fa-facebook-square"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
        </article>
    </section>
</footer>

<?php if (isset($neededScripts)): ?>
    <?php foreach ($neededScripts as $script): ?>
        <script type="text/javascript" src="<?= Router::getInstance()->getWwwPath()?>/js/<?= $script ?>?b=<?= date("YmdHis") ?>"></script>
    <?php endforeach; ?>
<?php endif; ?>
<script type="text/javascript" src="<?= Router::getInstance()->getWwwPath()?>/js/Basket.js"></script>
</body>
</html>